env:
  browser: true
  es6: true

extends: plugin:react/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  React: readonly
  $: readonly

parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: 11
  sourceType: module

plugins:
  - react

rules:
  semi:
    - error
    - never

  quotes:
    - error
    - double
